### ISSUE TITLE
Write a plot function to display 2D PointClouds

### ISSUE THREAD

**Issue by WorkGitAccount** [cs481-ekh/s24-meshers#55]
References #10 and useful for verifying #53 

As seen in the demo, it is useful for viewing and interacting with the current Point Cloud. 

- [ ] Plot function displays 2 dimensional plot of associated Point Cloud
- [ ] Write unit tests for the plot function. Verify it works

**Comment by paulvxx** [comment]
@WorkGitAccount  Is it okay if I work on this task?

**Comment by seanbsu** [comment]
- created the plot function and added the matplotlib library as a dependency to the DockerFile
- added the dependency to the lint test  .yml file
- added an all close assertion to the current elim so checks will pass until Tanner is done with his refactoring of those tests
- created a test file to test the plot function with data generated from the matlab code and had to eye test the resulting plots to see if they matched the plots produced by matlab's function. Since they are UI elements testing with code would be very difficult and probably require some other library to test
- implemented the plot function in Python then tested. One difference between the 2 is that matlab you can interact with the plot by hovering over points and such but matlab just produces a PNG file. It might be possible to create interactable plots but you require  something like tkinter 

[t:90]
