### ISSUE TITLE
Build constructor function

### ISSUE THREAD

**Issue by WorkGitAccount** [cs481-ekh/s24-meshers#86]
References #49

The constructor creates the levelsData in steps:

- [x] initializes and computes local variables
- [x] Initializes the structure for levels.
- [x] Compute all coarsened level nodes by calling PcCoarsen iteratively. 
- [x] For each level compute interpolator operators
       - Calls buildInterpOp() 
       - Builds Galerkin coarse level operator
       -

**Comment by WorkGitAccount** [comment]
Begin porting, reviewed code and current implementation.

[t:60]

**Comment by WorkGitAccount** [comment]
Reviewed python libraries needed for relevant matlab calls. Stepped over code and design decisions.

[t:45]

**Comment by seanbsu** [comment]
- testing out a way to compile the C code for demo purposes in a Docker container (e.g create the container from an image that properly mounts the project files then testing that the test.sh script runs correctly which has the  compile command in int) (big chunk of my time , 60+ min)
- updated branches with the current main changes
- set local branch to track the branch related to this task
- pushing my current implementation to the project making sure that Tanner doesnt have a similarly named file already in the branch
- added a polyharmonic file since we need one for no errors and that will come in Paul's task. So when pauls gets merged we just need to resolve the merge conflict by accepting his instead
- Continuing constructor implementation

[t:180]

**Comment by WorkGitAccount** [comment]
Working on my implementation simplified for the demo. Focusing on data types, indeces, and coarsen() calls. 

[t:90]

**Comment by seanbsu** [comment]
- working on making all imports work without errors
- added an import statement to 2d class for my implementation to test mine out simply need to comment out the other implementation and uncomment the import to test the file constructor.py implementation of the function
- one of my scipy imports wasnt being recoggnized and after some digging found it needed python versions 3.7 + but not anything above 3.10. So founda different function that didnt have such stringent python version requirements
- trying to figure out how to import the pcCoarsen function. Tanner might know better since he created the binding file to connect the cpp and python
[t:60]

**Comment by seanbsu** [comment]
docker run -it -v "C:\Users\scalk\Documents\seniordesign\s24-meshers":/app pymgm   
placing this docker command for creating the interactive container here so I can quickly grab it when needed.
for others who might be using it here's the general command

docker run -it -v </path/to/host/directory>:</path/in/container> <image_name_or_id> 

/path/to/host/directory for mine since im using windows using git bash I need the " " around the path  
/path/in/container if using our DockerFile to build the image then this should be /app

**Comment by seanbsu** [comment]
- figured out the right way to make the coarsen call but ran into an issue of the input size not being less than the outputsize for the elim function
- after some debugging it was how the loop is set up and instead of using j+1 in calculating Nc[j] sinze we are zero based in python it needs to be using j instead
- now the issue ios when calling the interopmethod the  fine level struct is oddly a list but the coarselevel struct is a np array i dont know why the levels data 0 is a list while levelsData[1] is the np array. it feels like they should both either be an np array or a list but not 1 of each
[t:60]

**Comment by seanbsu** [comment]
- made it so that the coarse and fine level structs are the same type by making the call to Coarsen a numpy array
- ensured that the sparse arrays being stored in levels data were of the csr type since multilevel needs them to be that way
- lh was being converted to a 600X1 matrix when it needed to stay as a 600x600 matrix for multilevel so I fixed it so it would stay that way 
- having issues importing the squrepoisson from the test file so i made a copy in utils and imported it into the demo from there
- got the demo to run through with no errors or warnings an answer is being recieved and the plot is working with the data being output
- the uh isnt being fully printed probably because it is a 2401x1 vector so that it probably too large to print. might see if we can use the matlibplot to plot it instead

[t:120]

**Comment by WorkGitAccount** [comment]
Continued with my implementation up to the PcCoarsen and BuildInterpOp calls. 

Ran into some errors importing and calling. Investigating the errors. 

[t:235]

**Comment by WorkGitAccount** [comment]
Fixed a bunch of imports. Not sure why they broke, but got it to work for now. Modules and imports seem to work for my version. Calling PcCoarsen works now but something still is off. Can reference Sean's implementation for calling solve and build interpOp. 

[t:100]
